### ISSUE TITLE
Decrypt wheat 

### ISSUE THREAD

**Issue by ghost** [itsTurnip/cryptscript#1]
Бро, там нет функции дешифровки в скрипте. Алсо написал бы доки для гумусов, иначе вообще ничего не понятно. Особенно работа с биграммами тьма тмущая.

**Comment by itsTurnip** [comment]
@Enteller, пардон за слоу-пост, только сейчас обнаружил висящий тикет. 
В качестве функции дешифровки для шифра Уитстона используется та же функция, что и для шифрования (в её описании это указано). 
Для работы с биграммами я пока ничего лучше уже реализованного варианта придумать не смог.
Доки не гарантирую ¯\\_(ツ)\_/¯

**Comment by itsTurnip** [comment]
На этом вопрос закрою. С биграммами пока ничего не придумывается, отложим до лучших времен.

**Comment by itsTurnip** [comment]
> 
> 
> С биграммами пока ничего не придумывается, отложим до лучших времен.

После последних коммитов выглядит чуть более читаемо.
